# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

# [[main]]
#   name = "Home"
#   url = "#about"
#   weight = 10

[[main]]
  name = "About"
  url = "#about"
  weight = 10

# [[main]]
#   name = "Posts"
#   url = "#posts"
#   weight = 20
[[main]]
  name = "Research"
  url = "/research"
  weight = 20

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 30

# [[main]]
#   name = "Publications"
#   url = "/publications_plain"
#   weight = 40

[[main]]
  name = "Publications"
  url = "/publication"
  weight = 45

[[main]]
  name = "Courses"
  url = "courses/"
  weight = 50


[[main]]
  name = "Resources"
  url = "#"
  hasChildren = true
  weight = 60

  [[main]]
    parent = "Resources"
    name = "Power System"
    url = "/resources/power_system"
    weight = 10
  [[main]]
    parent = "Resources"
    name = "Optimization"
    url = "/resources/optimization"
    weight = 20
  [[main]]
    parent = "Resources"
    name = "Writing"
    url = "/resources/writing"
    weight = 30
  [[main]]
    parent = "Resources"
    name = "LaTeX"
    url = "/resources/latex"
    weight = 40
  [[main]]
    parent = "Resources"
    name = "Plots"
    url = "/resources/plot"
    weight = 50
  [[main]]
    parent = "Resources"
    name = "Internal DB"
    url = "/resources/db"
    weight = 60


[[main]]
  name = "Contact"
  url = "/contact"
  weight = 70




# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
